### PR TITLE
Demo app

### PR DESCRIPTION
**Pull request by anhminh3105**
Hi @takatosp1.
i'd be nice for me to have you check out my demo (detection+classification):

the run commands that I used:
detection: python tools/run_net.py --cfg demo/AVA/SLOWFAST_32x2_R101_50_50.yaml
classification: python tools/run_net.py --cfg demo/Kinetics/SLOWFAST_8x8_R50.yaml

### CODE REVIEW

**Comment by lyttonhao** [comment]
Thanks a lot for @anhminh3105 to make this Demo contribution and @lequytra for merging into the latest codebase!

**Comment by takatosp1** [comment]
Thanks!

**Comment by anhminh3105** [comment]
My pleasure 😇

**Comment by windspirit95** [comment]
Thank you for your demo app. You really save our day.
However, I have one suggestion that since the sampling rate could be changed to higher, your demo could be delay significantly (the issue lying on the process around line 189 to 197). So you could change seq_len = cfg.DATA.NUM_FRAMES; and under code line 164 I added a condition as well as indenting the line 165:
if len(frames) % cfg.DATA.NUM_FRAMES == 1:
I have tested on my GPU 2080 SUPER and it could be significantly faster - 1.8s of processing time due to the frames size now is only 32 frames :)

**Pull request closed without merging**
